# Where are the target data stored? 
# Aperture 1 is assumed to be the target star!
'fnames':
  - "ASASSN-16kr/REDUCED/ucam/2019_09_27/target_ala2018.log"
  - "ASASSN-16kr/REDUCED/ucam/2019_09_28/target_ala2018.log"
  - "ASASSN-16kr/REDUCED/ucam/2019_09_29/target_ala2018.log"

'oname':  'ASASSN-16kr'
'lc_dir': 'LIGHTCURVES'

'target_coords': "22:05:59.48 -34:14:33.9"

'T0': 57658.2201330
'period': 0.061285932
'phase limits': [-0.5, 0.5]

# Atmospheric extinction coefficients. Calculated empirically for UCAM, NTT, super filters.
# Must be in CCD order of the logfile. This is typically r, g, u
'k_ext': [0.1129, 0.2020, 0.4868]
# Observatory name
'obsname': 'lasilla'
# CCD filter order
'bands': ['r', 'g', 'u']

# Comparison stars data
'comparison_aperture': '2'
'comparison_mags_tablename': 'comparison_star_sdss_mags'

'previous values': 'FOUND_VALUES.json'
